"""added design model

Revision ID: 1d107241945f
Revises: 89b4a43c9284
Create Date: 2023-04-27 09:41:21.264422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d107241945f'
down_revision = '89b4a43c9284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_pdinstances_designer_id_designers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pdinstances_design_id_designs'), 'designs', ['design_id'], ['id'])
        batch_op.drop_column('designer_id')

    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pieces_designer_id_designers'), 'designers', ['designer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pieces_designer_id_designers'), type_='foreignkey')
        batch_op.drop_column('designer_id')

    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_pdinstances_design_id_designs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pdinstances_designer_id_designers', 'designers', ['designer_id'], ['id'])
        batch_op.drop_column('design_id')

    op.drop_table('designs')
    # ### end Alembic commands ###
