"""create piece and pdinstance models

Revision ID: 42a73cfe0d2b
Revises: 3dafd1775e79
Create Date: 2023-04-24 22:20:42.499684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a73cfe0d2b'
down_revision = '3dafd1775e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdinstances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('designer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['designer_id'], ['designers.id'], name=op.f('fk_pdinstances_designer_id_designers')),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_pdinstances_piece_id_pieces')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdinstances')
    op.drop_table('pieces')
    # ### end Alembic commands ###
