"""add designer id to design

Revision ID: 59b3d510f45f
Revises: 6457489dce90
Create Date: 2023-04-27 15:14:59.603130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b3d510f45f'
down_revision = '6457489dce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_designs_designer_id_designers'), 'designers', ['designer_id'], ['id'])

    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pdinstances_designer_id_designers', type_='foreignkey')
        batch_op.drop_column('designer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pdinstances_designer_id_designers', 'designers', ['designer_id'], ['id'])

    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_designs_designer_id_designers'), type_='foreignkey')
        batch_op.drop_column('designer_id')

    # ### end Alembic commands ###
