"""added design model

Revision ID: 5c1b50a00ccc
Revises: 1d107241945f
Create Date: 2023-04-27 09:48:20.279927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1b50a00ccc'
down_revision = '1d107241945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pdinstances_designer_id_designers'), 'designers', ['designer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pdinstances_designer_id_designers'), type_='foreignkey')
        batch_op.drop_column('designer_id')

    # ### end Alembic commands ###
