"""add back the  pdinstances from designer model

Revision ID: 6457489dce90
Revises: ee29578da07d
Create Date: 2023-04-27 13:12:29.437730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6457489dce90'
down_revision = 'ee29578da07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pdinstances_designer_id_designers'), 'designers', ['designer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pdinstances_designer_id_designers'), type_='foreignkey')
        batch_op.drop_column('designer_id')

    # ### end Alembic commands ###
