"""add color columns

Revision ID: 6e2714fd39af
Revises: a75f64583b55
Create Date: 2023-05-04 12:29:28.036121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2714fd39af'
down_revision = 'a75f64583b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color5', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_column('color5')
        batch_op.drop_column('color4')
        batch_op.drop_column('color3')
        batch_op.drop_column('color2')
        batch_op.drop_column('color1')

    # ### end Alembic commands ###
