"""add city column to designer model

Revision ID: 89b4a43c9284
Revises: e6d4e01f2a7d
Create Date: 2023-04-26 11:51:21.922941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b4a43c9284'
down_revision = 'e6d4e01f2a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designers', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
