"""add position column

Revision ID: cc8ec006a5a6
Revises: 59b3d510f45f
Create Date: 2023-04-28 16:15:37.833601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8ec006a5a6'
down_revision = '59b3d510f45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
