"""remove designer id from pdinstance

Revision ID: ee29578da07d
Revises: 5c1b50a00ccc
Create Date: 2023-04-27 12:38:24.883793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee29578da07d'
down_revision = '5c1b50a00ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pdinstances_designer_id_designers', type_='foreignkey')
        batch_op.drop_column('designer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdinstances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pdinstances_designer_id_designers', 'designers', ['designer_id'], ['id'])

    # ### end Alembic commands ###
