"""add color column to piece model

Revision ID: f90472f5d702
Revises: 452ec5e98bd2
Create Date: 2023-04-24 22:33:39.195780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90472f5d702'
down_revision = '452ec5e98bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
